dimensions:
  x: 4
  r: 1 
  u: 2
actor_params:
  n_layers: 3
  n_units : 300
  tau:      0.01
  lr:       0.0001
critic_params:
  n_layers: 3
  n_units : 300
  tau:      0.01
  lr:       0.001
noise_params:
  delta: 0.5
  sigma: 0.5
  ou_a:  3.0
  ou_mu: 0.0
n_mem_objects:  5
memory_size:    100000
gamma:          0.99
b_size:         100
random_eps:     0.9
env_name:       CartPole-v1
n_episodes:     400
render:         False