dimensions:
  x:      4
  r:      1
  u:      2
actor:
  n_layers: 3
  n_units : 200
  tau:      0.01
  lr:       0.0001
critic:
  n_layers: 3
  n_units : 200
  tau:      0.01
  lr:       0.001
gamma:    0.98
b_size:   200
random_eps: 0.9