dimensions:
  x: 5
  r: 1 
  u: 2
actor_params:
  n_layers: 3
  n_units : 100
  tau:      0.01
  lr:       0.0001
critic_params:
  n_layers: 3
  n_units : 200
  tau:      0.01
  lr:       0.001
noise_params:
  delta: 0.5,0.2
  sigma: 0.5,0.7
  ou_a:  0.6,0.6
  ou_mu: 0.5,0.0
n_mem_objects:  8
memory_size:    100000
gamma:          0.99
b_size: 200
random_eps: 0.3


# ROLLOUT RELATED CONFIG
eval_after: 20
train_rollout:
  n_episodes: 400000
  render: False
  periodic_ckpt: 100
  train_cycles_per_ts: 10
eval_rollout:
  n_episodes: 10
  render: True
  periodic_ckpt: False
  save_best: True