ddpg:
  n_agents: 3
  inputs:
    f_goal: 3
    multi:
      state: 8
      t_goal: 2
      action: 2
  actor_params:
    dim_action: 2
    n_layers: 3
    n_units : 100
    tau:      0.01
    lr:       0.0001
  critic_params:
    n_layers: 3
    n_units : 200
    tau:      0.01
    lr:       0.001
  noise_params:
    delta: 0.5,0.2
    sigma: 0.5,0.7
    ou_a:  0.6,0.6
    ou_mu: 0.5,0.0
  n_mem_objects: 8
  memory_size: 100000
  b_size: 200